spring.application.name=Farmacia_grupo06
# Driver SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DB_PRUEBA;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

jwt.secret=clave-super-secreta-de-al-menos-32-caracteres-para-HS256
jwt.expiration=86400000


# Puerto
server.port=8081